name: hotel_in
description: Hotel in – Plan your next awesome trip!

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.1.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_gen: ^5.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  flutter_gen_runner: ^5.10.0

flutter_gen:
  output: lib/gen

flutter:
  uses-material-design: true
  assets:
    # SVG icons
    - assets/logo.svg
    - assets/searchIcon.svg
    - assets/userIcon.svg
    - assets/calenderIcon.svg
    - assets/locationIcon.svg
    - assets/starIconFilled.svg
    - assets/arrowIcon.svg
    - assets/starIconOutlined.svg
    - assets/instagramIcon.svg
    - assets/facebookIcon.svg
    - assets/twitterIcon.svg
    - assets/linkendinIcon.svg
    - assets/freeWifiIcon.svg
    - assets/freeBreakfastIcon.svg
    - assets/roomServiceIcon.svg
    - assets/mountainIcon.svg
    - assets/poolIcon.svg
    - assets/homeIcon.svg
    - assets/closeIcon.svg
    - assets/locationFilledIcon.svg
    - assets/heartIcon.svg
    - assets/badgeIcon.svg
    - assets/menuIcon.svg
    - assets/closeMenu.svg
    - assets/guestsIcon.svg
    - assets/addIcon.svg
    - assets/dashboardIcon.svg
    - assets/listIcon.svg
    - assets/uploadArea.svg
    - assets/totalBookingIcon.svg
    - assets/totalRevenueIcon.svg

    # PNG images
    - assets/roomImg1.png
    - assets/roomImg2.png
    - assets/roomImg3.png
    - assets/roomImg4.png
    - assets/regImage.png
    - assets/exclusiveOfferCardImg1.png
    - assets/exclusiveOfferCardImg2.png
    - assets/exclusiveOfferCardImg3.png
